name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        run: |
          scp -r -o StrictHostKeyChecking=no ./* github-action-user@${{ secrets.SERVER_IP }}:/home/github-action-user/api

      - name: Remove old container
        run: |
          ssh github-action-user@${{ secrets.SERVER_IP }} "docker stop api && docker rm api"
      
      - name: Remove old image
        run: |
          ssh github-action-user@${{ secrets.SERVER_IP }} "docker image rm api"

      - name: Build container
        run: |
          ssh github-action-user@${{ secrets.SERVER_IP }} "docker build -t api ."

      - name: Run container
        run: |
          ssh github-action-user@${{ secrets.SERVER_IP }} "docker run -n api -d --network=host --restart=always -it api"
